"""
389. Find the Difference
Easy

2713

381

Add to List

Share
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
"""
import collections
from typing import List, Optional
from helpers.TreeNode import TreeNode


# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        pass


if __name__ == "__main__":
    sol = Solution()
    s = "abcd"
    t = "abcds"
    res = sol.findTheDifference(s, t)
    print("Ans is ", res)
